"""update missing fields

Revision ID: 56397b41bc20
Revises: 0e025f4f00e8
Create Date: 2022-04-24 18:10:19.955553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56397b41bc20'
down_revision = '0e025f4f00e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'past_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('past_shows', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
