"""update name constrains

Revision ID: 71849929ce7a
Revises: 
Create Date: 2022-05-02 14:30:21.619654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71849929ce7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Venue', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='unique')
    # ### end Alembic commands ###
